name: example
description: The demo app of flui.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.9.2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  event_bus: ^1.1.1
  shared_preferences: ^0.5.6+1
  url_launcher: ^5.4.1

  flui:
    path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cloud66.png
    - assets/inspector.png
    - assets/pullass.png
    - assets/sentry.png
    - assets/sider.png
    - assets/test.png
    - assets/backhub.png
    - assets/share_friend.png
    - assets/share_weibo.png
    - assets/avatar.jpg
    - assets/nodata.png
    - assets/poster.png
    - assets/google.png
    - assets/instagram.png
    - assets/keynote.png
    - assets/mail.png
    - assets/messages.png
    - assets/omnifocus.png
    - assets/poster.png
    - assets/twitter.png
    - assets/whatsapp.png
    - assets/word.png
    - assets/google+.png
    - assets/button.png
    - assets/label.png
    - assets/navi.png
    - assets/toast.png
    - assets/bubble.png
    - assets/avatar.png
    - assets/input.png
    - assets/badge.png
    - assets/empty.png
    - assets/notice.png
    - assets/skeleton.png
    - assets/sheet.png
    - assets/list.png
    - assets/logop.png
    - assets/record.gif
    - assets/logo_trans.png
    - assets/no_data_dark.png
    - assets/button_dark.png
    - assets/label_dark.png
    - assets/count_stepper.png
    - assets/count_stepper_dark.png
    - assets/navi_dark.png
    - assets/toast_dark.png
    - assets/bubble_dark.png
    - assets/avatar_dark.png
    - assets/input_dark.png
    - assets/badge_dark.png
    - assets/empty_dark.png
    - assets/notice_dark.png
    - assets/skeleton_dark.png
    - assets/sheet_dark.png
    - assets/list_dark.png
    - assets/iron_man.png
    - assets/dev.png
    - assets/folder_b.png
    - assets/folder_r.png
    - assets/folder_y.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
